[package]

authors = ["Christian Sdunek <me@systemcluster.me>"]
build = "build.rs"
categories = ["compression", "filesystem", "command-line-utilities"]
description = "Packer for Executables"
edition = "2018"
include = [
  "Cargo.toml",
  "src/**/*",
  "startpe/**/*",
  "build.rs",
  "LICENSE",
]
license = "BSD-2-Clause"
name = "wrappe"
readme = "README.md"
repository = "https://github.com/Systemcluster/wrappe"
version = "0.0.0"

[[bin]]

name = "wrappe"
path = "src/main.rs"

[workspace]

members = [
  ".",
  "startpe",
]

[profile.release]

codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "thin"
opt-level = 's'
panic = "abort"

[dependencies]

minilz4 = "0.4.0"
staticfilemap = "0.1.2"

clap = {package = "clap", version = "3.0.0-beta.2"}
color-backtrace = "0.4.2"
console = "0.12.0"
indicatif = "0.15.0"
jwalk = "0.5.1"
num_cpus = "1.13.0"
path-slash = "0.1.3"
rand = "0.7.3"
rayon = "1.4.0"
sysinfo = "0.15.2"
twox-hash = "1.5.0"
zerocopy = "0.3.0"

[build-dependencies]

jwalk = "0.5.1"
which = "4.0.2"
