[package]

authors = ["Christian Sdunek <me@systemcluster.me>"]
build = "build.rs"
categories = ["compression", "filesystem", "command-line-utilities"]
description = "Packer for Executables"
edition = "2018"
include = [
  "Cargo.toml",
  "src/**/*",
  "startpe/**/*",
  "build.rs",
  "LICENSE",
]
license = "BSD-2-Clause"
name = "wrappe"
readme = "README.md"
repository = "https://github.com/Systemcluster/wrappe"
version = "0.0.0"

[[bin]]

name = "wrappe"
path = "src/main.rs"

[workspace]

members = [
  ".",
  "startpe",
]

[profile.release]

codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
panic = "abort"

[dependencies]

staticfilemap = {version = "0.1.5", default-features = false, features = ["zstd"]}

clap = {package = "clap", version = "3.0.0-beta.2"}
color-backtrace = "0.5.0"
console = "0.14.0"
indicatif = "0.15.0"
jwalk = "0.6.0"
num_cpus = "1.13.0"
path-slash = "0.1.4"
rand = "0.8.2"
rayon = "1.5.0"
sysinfo = "0.15.9"
twox-hash = {version = "1.6.0", default-features = false}
zerocopy = "0.3.0"
zstd = "0.6.0"

[build-dependencies]
jwalk = "0.6.0"
which = "4.0.2"
