[package]

authors = ["Christian Sdunek <me@systemcluster.me>"]
description = "Runner for Packed Executables"
edition = "2018"
license = "BSD-2-Clause"
name = "startpe"
publish = false
repository = "https://github.com/Systemcluster/wrappe"
version = "0.0.0"
workspace = ".."

[[bin]]

name = "startpe"
path = "src/main.rs"

[dependencies]

dirs = "3.0.1"
filetime = "0.2.12"
fslock = "0.1.6"
memmap = "0.7.0"
rayon = "1.4.1"
twox-hash = {version = "1.6.0", default-features = false}
zerocopy = "0.3.0"
zstd = "0.5.3"

[target.'cfg(windows)'.dependencies]

winapi = {version = "0.3.9", features = [
  "wincon",
  "wincontypes",
  "consoleapi",
]}
